version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iris
    ports:
      - 1972
      - 63077:52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev
    
    # Put your timezone here (available list code here https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
    environment:
      - TZ=${TZ:-Europe/Paris}

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GRAFANA_INFLUX_API_KEY=${GRAFANA_INFLUX_API_KEY}
      - INFLUX_ORG=${INFLUX_ORG}
    ports:
      - 3000:3000
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources

  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - 8086:8086
    volumes:
      - ./influxdb2-storage:/var/lib/influxdb2
      - ./influxdb2-config:/etc/influxdb2
      - ./init-influxdb.sh:/docker-entrypoint-initdb.d/init-influxdb.sh
      # useful for first start, it allows to init-influxdb.sh to set API KEYS in the .env file
      - ./.env:/etc/telegraf/docker-envfile.txt

    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD:-sysadmin}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG:-dc}
      - DOCKER_INFLUXDB_INIT_BUCKET=IRIS_SQL_STATS
      - DOCKER_INFLUXDB_INIT_RETENTION=0

  telegraf:
    image: telegraf
    container_name: telegraf
    command: [ "--config-directory", "/etc/telegraf/config" ]
    volumes:
      - ./telegraf/config:/etc/telegraf/config
      - ./telegraf/in:/etc/telegraf/in
      - ./telegraf/done:/etc/telegraf/done
      - ./telegraf/err:/etc/telegraf/err
    environment:
      - INFLUX_TOKEN=${TELEGRAF_INFLUX_API_KEY}
      - INFLUX_ORG=${INFLUX_ORG:-dc}
      - IRIS_USER=${IRIS_USER}
      - IRIS_PASSWORD=${IRIS_PASSWORD}
    depends_on:
      - influxdb2

  # grafanatest:
  #   image: grafana/grafana-oss
  #   environment:
  #     - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
  #     - GRAFANA_INFLUX_API_KEY=${GRAFANA_INFLUX_API_KEY}
  #     - INFLUX_ORG=${INFLUX_ORG}
  #   ports:
  #     - 3001:3000
  #   volumes:
  #     - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
  #     - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards