{
 "title": "InfluxDB - SQL Stats",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "measurement",
    "label": "Stats",
    "query": "Daily : sqlstats_daily, Hourly : sqlstats_hourly"
   },
   {
    "name": "iris_server_name",
    "label": "Server Name",
    "query": {
     "query": "from(bucket: \"IRIS_SQL_STATS\")\r\n  |> range(start: $__from/1000, stop: $__to/1000)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\r\n  |> keep(columns: [\"server_name\"])\r\n  |> unique(column: \"server_name\")\r\n"
    }
   },
   {
    "name": "iris_instance_name",
    "label": "Instance",
    "query": {
     "query": "from(bucket: \"IRIS_SQL_STATS\")\r\n  |> range(start: $__from/1000, stop: $__to/1000)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.server_name == \"${iris_server_name}\")\r\n  |> keep(columns: [\"instance_name\"])\r\n  |> unique(column: \"instance_name\")"
    }
   },
   {
    "name": "iris_namespace",
    "label": "NameSpace",
    "query": {
     "query": "from(bucket: \"IRIS_SQL_STATS\")\r\n  |> range(start: $__from/1000, stop: $__to/1000)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.server_name == \"${iris_server_name}\" and r.instance_name == \"${iris_instance_name}\")\r\n  |> keep(columns: [\"namespace\"])\r\n  |> unique(column: \"namespace\")"
    }
   },
   { "name": "iris_sql_hash", "label": "SQL Hash" }
  ]
 },
 "panels": [
  { "title": "Data Source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily SQL Stats",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"IRIS_SQL_STATS\")\r\n  |> range(start: $__from/1000, stop: $__to/1000)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" \r\n    and r.instance_name == \"${iris_instance_name}\" \r\n    and r.server_name == \"${iris_server_name}\" \r\n    and r.namespace == \"${iris_namespace}\"\r\n  )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"count\", \"commands\", \"execution_time\", \"row_count\", \"statement\", \"hash\"])\r\n  |> filter(fn: (r) => \"${iris_sql_hash}\" == \"\" or r.hash == \"${iris_sql_hash}\")\r\n"
    }
   ]
  },
  { "title": "Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Number Of SQL",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    { "panelId": 1 }
   ]
  },
  {
   "title": "Execution Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "panelId": 1 }
   ]
  },
  {
   "title": "Row Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    { "panelId": 1 }
   ]
  },
  {
   "title": "Number of SQL by namespace for the period",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IRIS_SQL_STATS\")\r\n  |> range(start: $__from/1000, stop: $__to/1000)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" \r\n    and r.instance_name == \"${iris_instance_name}\" \r\n    and r.server_name == \"${iris_server_name}\" \r\n  )\r\n  |> filter(fn: (r) => r._field == \"count\")\r\n  |> group(columns: [\"namespace\"])\r\n  |> sum(column: \"_value\")\r\n  |> keep(columns: [\"namespace\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Execution Time by namespace for the period",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IRIS_SQL_STATS\")\r\n  |> range(start: $__from/1000, stop: $__to/1000)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" \r\n    and r.instance_name == \"${iris_instance_name}\" \r\n    and r.server_name == \"${iris_server_name}\" \r\n  )\r\n  |> filter(fn: (r) => r._field == \"execution_time\")\r\n  |> group(columns: [\"namespace\"])\r\n  |> sum(column: \"_value\")\r\n  |> keep(columns: [\"namespace\", \"_value\"])"
    }
   ]
  },
  {
   "title": "RowCount by namespace for the period",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IRIS_SQL_STATS\")\r\n  |> range(start: $__from/1000, stop: $__to/1000)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" \r\n    and r.instance_name == \"${iris_instance_name}\" \r\n    and r.server_name == \"${iris_server_name}\" \r\n  )\r\n  |> filter(fn: (r) => r._field == \"row_count\")\r\n  |> group(columns: [\"namespace\"])\r\n  |> sum(column: \"_value\")\r\n  |> keep(columns: [\"namespace\", \"_value\"])"
    }
   ]
  }
 ]
}